DROP TRIGGER IF EXISTS trg_stock_movements_balance        ON stock_movements;
DROP TRIGGER IF EXISTS trg_locations_updated_at           ON locations;
DROP TRIGGER IF EXISTS trg_roles_updated_at               ON roles;
DROP TRIGGER IF EXISTS trg_loyalty_rules_updated_at       ON loyalty_rules;
DROP TRIGGER IF EXISTS trg_users_updated_at               ON users;
DROP TRIGGER IF EXISTS trg_categories_updated_at          ON categories;
DROP TRIGGER IF EXISTS trg_products_updated_at            ON products;
DROP TRIGGER IF EXISTS trg_suppliers_updated_at           ON suppliers;
DROP TRIGGER IF EXISTS trg_ingredients_updated_at         ON ingredients;
DROP TRIGGER IF EXISTS trg_purchase_orders_updated_at     ON purchase_orders;
DROP TRIGGER IF EXISTS trg_inventory_counts_updated_at    ON inventory_counts;
DROP TRIGGER IF EXISTS trg_recipes_updated_at             ON recipes;
DROP TRIGGER IF EXISTS trg_orders_updated_at              ON orders;
DROP TRIGGER IF EXISTS trg_shifts_updated_at              ON shifts;
DROP TRIGGER IF EXISTS trg_payroll_updated_at             ON payroll_records;
DROP TRIGGER IF EXISTS trg_accounts_updated_at            ON accounts;
DROP TRIGGER IF EXISTS trg_tax_records_updated_at         ON tax_records;
DROP TRIGGER IF EXISTS trg_loyalty_accounts_updated_at    ON loyalty_accounts;
DROP TRIGGER IF EXISTS trg_customers_updated_at           ON customers;
DROP TRIGGER IF EXISTS trg_payment_methods_updated_at     ON payment_methods;
DROP FUNCTION IF EXISTS update_ingredient_balance();
DROP FUNCTION IF EXISTS set_updated_at();
